name: hasaad
description: "Hasaad is a smart farming application that helps farmers make better, data-driven decisions in real time."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.6.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.2.1
  geolocator: ^12.0.0
  table_calendar: ^3.1.2
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.5.2
  share_plus: ^10.1.4
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/l10n/
    - "assets/logo no text.png"
    - "assets/logo with text.png"
    - "assets/logo no text - white.png"
    - "assets/logo with text - white.png"
    - "assets/logo no text - nav bar.png"
    - "assets/onboarding-1.avif"
    - "assets/onboarding-2.avif"
    - "assets/onboarding-3.avif"
    - assets/splash_icon.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash_icon.jpg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash_icon.jpg"
  android_12:
    image: "assets/splash_icon.jpg"
    color: "#ffffff"
